.Dd Jan 30, 2024
.Dt gorg64_spktone 1
.Os
.Sh NAME
.Nm gorg64_spktone
.Nd GALAXY ORGANIZER Sound generator for PC-speaker.
Run: gorg64_spktone f 100 for signal 100 Hz
Run: gorg64_spktone t 100 for signal 100 speaker units (1193280 / tone)
Run: gorg64_spktone d 1 cycle of increase tones in 1 ms.
For speaker on/off
use gorg64_spkon and gorg64_spkoff , exclude key "d".
